travis/tc3_pragmalint.sh
Using process substitution to instead run it in the same shell such that the modified value will be used. _bash_ 👀 
Closes #7
=> FIX: EXIT_CODE was being set in a subshell

travis/init.sh, travis/settings.sh, travis/tc3_style/check.sh, travis/tc3_style/files.sh, travis/tc3_style/fix.sh, travis/tc3_style/parse.sh
Borrowed from https://github.com/pcdshub/lcls-plc-lfe-motion/blob/master/style/fix_style.sh (with an attempt to keep `git blame` correct...)
Untested as of yet. Intention is to have style checks be required to satisfy, but blark parsing just a warning until it is improved.
The check for a non-zero length string is also dumb here, as we don't do anything with "$TWINCAT_STYLE". This will probably all require a refactor down the road anyway...
=> ENH: add twincat 3 style checks from lcls-plc-lfe-motion

README.md, example_twincat_travis.yml, travis/tc3_style/check.sh, travis/tc3_style/files.sh
- Show which files/lines had issues
- Allow user to configure files to exclude from the check via regex
- Add TWINCAT_STYLE to the readme and example
- Add success message for passing checks
- Make only leading tabs fail the tab check, e.g. this is not allowed:
```
<tab>bMyBool: BOOL
bMyOtherBool: BOOL
```
But this is ok:
```
bMyBool:<tab>BOOL
bMyOtherBool:<tab>BOOL
```
Since not allowing this will be (has been) really disruptive
=> ENH: TwinCAT Style Check Expanded

README.md, example_python_travis.yml, example_twincat_travis.yml, travis/init.sh, travis/pre_commit.sh
Adds a new option to check the pre-commit on Travis by setting `PRE_COMMIT=1`.
Based on https://github.com/pcdshub/pre-commit-hooks/issues/4
closes #12 
In addition to the above:
- Provides links for people not familiar with pre-commit to read the docs or set up their repo
- Shows a git diff after a pre-commit failure to make it clear what needs to be fixed
Example succeeding build: https://travis-ci.org/github/ZLLentz/lcls2-cc-lib/jobs/678286604
Example failing build: https://travis-ci.org/github/ZLLentz/lcls2-cc-lib/jobs/678288717
=> ENH: Add pre-commit CI helper

travis/init.sh
Simple fix to allow the old variable `LINT_PYTHON` to continue to be used.
Tested here: https://travis-ci.com/github/ZryletTC/typhos/jobs/338177444
=> BUG: Re-add support for old lint variable

README.md, example_twincat_travis.yml, travis/docs_template_files/source/conf.py, travis/docs_template_files/source/index.rst, travis/shared_configs/twincat/docs-build.yml, travis/shared_configs/twincat/doctr-upload.yml, travis/shared_configs/twincat/pragmalint.yml, travis/shared_configs/twincat/pre-commit.yml, travis/shared_configs/twincat/setup.yml, travis/shared_configs/twincat/standard.yml, travis/shared_configs/twincat/style.yml, travis/shared_configs/twincat/summary.yml, travis/tc3_style/adsIoc.dbd
* New style shared configurations, relying on `ads-deploy` and some previously created scripts (style checking, pre-commit checks).
* May still have some bugs, but this is working for the test project: https://github.com/klauer/lcls-twincat-optics/blob/master/.travis.yml
* Documentation relies on new, configurable template repository: https://github.com/pcdshub/twincat-docs-template
* Includes vendored `adsIoc.dbd` for dbd-based linting of record fields
* Example documentation output using doctr-versions-menu: https://klauer.github.io/lcls-twincat-optics/ (note there is no actual difference between master and the versions listed there)
* Example travis output: https://travis-ci.com/github/klauer/lcls-twincat-optics/builds/172549255
=> Twincat shared configs

travis/shared_configs/twincat/docs-build.yml
Pairs with https://github.com/pcdshub/twincat-docs-template/commit/eb95404a8feca6b61ce656cc459d2f26445c643f
so we can get the readthedocs theme to replace the minimal (subjectively ugly) alabaster theme...
Example
=> MNT: allow docs template to specify requirements

travis/shared_configs/standard-python-conda.yml
It's not possible for packages to fix their requirements due to #40.
Remove package linter from default config until issues are addressed for all our packages.
=> MNT: remove broken package linter from default config

travis/shared_configs/doctr-upload.yml
This is a fix for the issue that we are having with `doctr-versions-menu` reported here:
- https://github.com/pcdshub/typhos/issues/375
and here:
- https://github.com/goerz/doctr_versions_menu/issues/8
We can remove this forced upgrade to `pyparsing` once the new dependency restriction is added into the package.
I tested this with testproject1234 and it works as expected: https://travis-ci.com/github/hhslepicka/testproject1234/jobs/366840848
=> HACK/FIX: Force updating pyparsing for Docs Deploy

travis/shared_configs/anaconda-build.yml, travis/shared_configs/docs-build.yml, travis/shared_configs/python-benchmark.yml, travis/shared_configs/python-tester-conda.yml
This ensures that we always get the correct priority e.g.:
bld-dir > conda-forge > pcds-tag
https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-channels.html#strict-channel-priority
Is there any easy way to test this on my failing repo before merging here?
=> MNT: Set channel_priority to strict

travis/shared_configs/docs-build.yml
=> CI: build docs on 3.7, not 3.9

travis/shared_configs/docs-build.yml
=> CI: docs on Python 3.6, not 3.7

travis/shared_configs/anaconda-upload.yml, travis/shared_configs/docs-build.yml, travis/shared_configs/doctr-upload.yml, travis/shared_configs/package-linter.yml, travis/shared_configs/python-benchmark.yml, travis/shared_configs/python-tester-conda.yml, travis/shared_configs/python-tester-pip.yml
- As per NEP29, we could have dropped py36 support as early as last year: https://numpy.org/neps/nep-0029-deprecation_policy.html
- python 3.6 does not have dataclasses
- python 3.8 is live on the floor
- python 3.9 exists and I'd like to make it live on the floor at some point
Tried this on typhos at https://travis-ci.com/github/pcdshub/typhos/builds/232184349
Closes #61 (contains it basically)
Closes #60
=> MNT: drop py36, default py38, add py39

travis/shared_configs/python-tester-pip.yml
- Use python 3.9 in the CI pip testing, because that's what we're running in prod now
- Change the stage name to "Python - PIP" because for the builds that allow failures on PIP it's annoying to change the string every time.
=> ENH: push pip testing forward a bit, future-proof the build stage name

README.md, travis/shared_configs/docs-build.yml, travis/shared_configs/python-tester-conda-latest.yml, travis/shared_configs/standard-python-conda-latest.yml
`pcdsdevices` is the first module that is going 3.9 only (admittedly, mostly because it can and also because I want free reign to use all new language features). Here are some adjustments to the CI to accommodate this.
- Move Sphinx docs to Python 3.9. This allows packages that are 3.9-only to run docs builds.
- Add standard option for testing with prod python and up only. This allows packages that are 3.9-only to run their CI without any extra allow_failures builds.
- Adjust some information in the readme because I noticed it was outdated while scrolling through.
=> CI: Various updates for pcdsdevices CI

travis/shared_configs/python-linter.yml
I have a job that's failing because I have code that throws a syntax error on python versions before 3.8, and is picked up as such by the python 3.6 flake8 that travis is running. It creates a funny build where all the tests pass, and then I'm also alerted about a syntax error.
This changes the python linter config to run on python 3.9 instead of on the default travis python version, which is apparently 3.6
=> CI: run the python linter against py3.9

travis/shared_configs/standard-python-conda-latest.yml, travis/shared_configs/standard-python-conda.yml
X server and window manager can be confusing if forgotten, leading to segfaulting CI failures.
I'm voting to take the CI performance hit and just run our ui setup by default.
I think these imports should do it - what do you think, @ZLLentz @ZryletTC ?
=> CI: by default, start up the X server

travis/shared_configs/python-tester-pip.yml
Set the matplotlib backend to avoid unknown pyqt/bluesky bug in the pip builds
These have been failing with cryptic abort messages that seem related to a strange background thread interaction between these libraries on these builds during unit testing suites only on travis only
=> MAINT: set MPLBACKEND=agg for pip

travis/shared_configs/python-pre-commit.yml, travis/shared_configs/standard-python-conda-latest.yml, travis/shared_configs/standard-python-conda.yml
As in the title: we'd like to expand from just a flake8 check to a full pre-commit check.
See https://github.com/pcdshub/pcdsdevices/issues/1002
=> CI: switch in the pre-commit check instead of only a flake8 check

.travis.yml, README.md, example_python_travis.yml, travis/shared_configs/python-tester-conda.yml
https://numpy.org/neps/nep-0029-deprecation_policy.html
Admittedly this is entirely because py37 is segfaulting for typhos in the CI
=> MAINT: drop py37 builds as per NEP29

travis/shared_configs/python-tester-conda-latest.yml, travis/shared_configs/python-tester-conda.yml, travis/shared_configs/python-tester-pip.yml
Possible solution for #79 
~It would be nice if we had a `PYTHON_MODULE_NAME` environment variable in general. We could limit the scope of the coverage more specifically here, instead of including `setup.py` etc.~ On second thought, that probably belongs in either `.coveragerc` or `pyproject.toml`
Closes #79
=> REF: try pytest-cov instead of using 'coverage run'

travis/shared_configs/python-tester-conda-latest.yml, travis/shared_configs/python-tester-conda.yml, travis/shared_configs/python-tester-pip.yml
Testing lightpath failures in a docker container showed that my bash knowledge still has a way to go:
* Quotes are not required when appending to the array
* In fact, they get included as-is when running pytest
* Additionally, a mistaken single quote caused for the log filename to not be expanded
=> FIX: pytest_args, again

travis/shared_configs/python-tester-conda-latest.yml, travis/shared_configs/python-tester-conda.yml
This is in preparation for the eventual upgrade to python 3.10
- Add python 3.10 test stages to the standard and latest python checkers
- Set these new stages as default/mandatory allow_failure
Once we deploy python 3.10, then the following changes could be made:
- "latest" config could stop testing on 3.9
- no more default/mandatory allow_failure on 3.10
- make the pypi build and others use 3.10 instead of 3.9
=> ENH: test against python 3.10

travis/shared_configs/twincat/setup.yml
Closes #89
See https://app.travis-ci.com/github/pcdshub/lcls-twincat-vacuum/jobs/590814009, for example:
```
Traceback (most recent call last):
File "/home/travis/miniconda/lib/python3.9/site-packages/sphinx/config.py", line 350, in eval_config_file
exec(code, namespace)
File "/home/travis/docs/source/conf.py", line 18, in <module>
import doctr_versions_menu
File "/home/travis/miniconda/lib/python3.9/site-packages/doctr_versions_menu/__init__.py", line 14, in <module>
from . import cli, ext
File "/home/travis/miniconda/lib/python3.9/site-packages/doctr_versions_menu/cli.py", line 15, in <module>
from .version_data import get_version_data
File "/home/travis/miniconda/lib/python3.9/site-packages/doctr_versions_menu/version_data.py", line 10, in <module>
from .groups import get_groups
File …
```
=> MAINT: pin packaging back for the twincat builds to avoid a removal

.github/workflows/twincat-standard.yml
python-docs requires a package-name setting. 
We re-use this workflow for TwinCAT jobs which have no Python package.
* A consequence of changes in #91 
* In future, if package name gets used in `python-docs.yml`, we'll need to check that `package-name` is not empty prior to using it
* Revealed in https://github.com/pcdshub/pcds-ci-test-repo-twincat/actions/runs/3888276083
=> FIX: python-docs requires package-name to be set, even for twincat

.github/workflows/python-docs.yml
Side-effect of #95 - docs deployment was failing.
Test repo tests indicate this works now: 
https://github.com/pcdshub/pcds-ci-test-repo-python/actions/runs/3961843579/jobs/6787770412
https://github.com/pcdshub/pcds-ci-test-repo-python/commit/4a546f778f8a988485801983f776402f3f974df9
=> FIX: docs are in ./ and not ./html

.github/workflows/twincat-standard.yml
* Left my repository name and branch in here accidentally
* Fixed to use: https://github.com/pcdshub/twincat-docs-template (master)
=> FIX: doc template repository name

.github/workflows/python-conda-test.yml, .github/workflows/python-docs.yml, .github/workflows/python-pip-test.yml, .github/workflows/python-standard.yml
* Add `system-packages` input to conda, pip, and docs workflows
* Add `pip-system-packages`, `conda-system-packages`, and `docs-system-packages` to standard reused Python workflow input
Used in: https://github.com/pcdshub/whatrecord/pull/152
=> ENH: allow system package installation in Python testing workflows

.github/workflows/python-conda-test.yml, .github/workflows/python-docs.yml, .github/workflows/python-pip-test.yml, .github/workflows/twincat-pragmalint.yml, .github/workflows/twincat-style.yml, .github/workflows/twincat-summary.yml, .github/workflows/twincat-syntax.yml
* TwinCAT repositories such as https://github.com/pcdshub/lcls-twincat-motion have submodules with library source code
* For the tools to have a full view of all enclosed source code, we need to make all checkouts recursive for TwinCAT jobs
* We typically don't use submodules in our Python repositories, but it seems a reasonable default to use regardless
=> MNT: GHA - make all checkouts recursive

.github/workflows/twincat-pragmalint.yml
* plc-tmo-vac is skipping over files for some bizarre reason: https://github.com/pcdshub/lcls-plc-tmo-vac/actions/runs/4429313692/jobs/7769595993
* I can reproduce this locally with just a simple bash script on the tmo project:
```bash
#!/bin/bash
while IFS= read -r -d '' source_filename; do
echo "Checking ${source_filename}"
done < <(find "." -type f -iname '*.TcDUT' -or -iname '*.TcGVL' -or -iname '*.TcPOU' -print0)
```
```
$ find . -name "*.Tc*" |wc -l
33
(^ this includes 3 TcTTO files we don't care about so our target is 30 files)
$ bash reproducing_gha.sh  |wc -l
19
$ bash pr.sh | wc -l
30
```
(If someone can clue me in what I'm doing wrong there - I'd certainly appreciate it...)
In the meantime, the workaround in this PR seems to be fine as in the above file count listing.
=> REF: replace find-with-or with function

.github/workflows/python-standard.yml
Continuing on with the guesswork, it seems likely that we'll need an 'inherit secrets' setting for each of our pip/conda matrices.
Ideally, it'd only inherit secrets for the 3.9 release job - but let's keep this simpler for now.
Ref: https://github.com/pcdshub/whatrecord/pull/157
=> FIX: inherit secrets for pip/conda jobs

.github/workflows/python-pip-test.yml
* Warn if TWINE_PASSWORD unset
* Use verbose mode for `twine upload`
=> MNT: check pypi token and use twine verbose mode

.github/workflows/python-conda-test.yml
Unquote the glob
ref https://github.com/pcdshub/happi/actions/runs/4642229322/jobs/8245410768
```
Error:  File "/home/runner/conda-bld/noarch/*.tar.bz2" does not exist
```
Locally:
```
zlentz@psbuild-rhel7-03:~$ cat "*.py"
cat: *.py: No such file or directory
zlentz@psbuild-rhel7-03:~$ cat *.py
from pydm import Display
from pydm.widgets.label import PyDMLabel
from qtpy.QtCore import QTimer
from qtpy.QtWidgets import QVBoxLayout
```
just bash things
=> FIX: quoted glob is a literal asterisk

.github/workflows/twincat-style.yml, .github/workflows/twincat-syntax.yml
_If you needed more evidence I have no idea what I'm doing, here's another PR for you._
This might be enough to get non-code PRs to stop bailing early on GitHub Actions.
Example: https://github.com/pcdshub/lcls-plc-rixs-optics/actions/runs/4694495047/jobs/8322692880
=> MNT: maybe fix empty source file check

.github/workflows/python-docs.yml
Looks like tagged documentation deployment got messed up somewhere along the way during my CI helper development. I think this might resolve it but am open to input:
https://github.com/pcdshub/lcls-plc-rixs-optics/actions/runs/4694264771/jobs/8322282257
=> DOC: attempt at fixing tagged docs deployment

.github/workflows/python-conda-test.yml
Properly trigger pcds-dev deployment in conda tests.  
`github.event.pull_request` doesn't seem to exist for merge commits, so filtering for `push` events to the master branch is used as a proxy.  This should be relatively bulletproof, since we don't permit direct pushes to master... right?
This matches the pattern seen in the [pip tests (pypi deployment)](https://github.com/pcdshub/pcds-ci-helpers/blob/05492d57be61fa089fa7ef97056c630c114aee2c/.github/workflows/python-pip-test.yml#L218) and [pcds-tag deployment](https://github.com/pcdshub/pcds-ci-helpers/blob/05492d57be61fa089fa7ef97056c630c114aee2c/.github/workflows/python-conda-test.yml#L242)
=> BLD: Fix dev deployment step conditional

.github/workflows/twincat-style.yml, .github/workflows/twincat-syntax.yml
Closes #123 (unless I did something else dumb)
Our goal with the `diff-tree` stuff is to see the files that changed, then only run the experimental syntax check on them because it's a slow process.
The existing implementation is broken when files are moved, causing CI to fail PR jobs.
The fix is that `diff-tree` arguments were erroneously swapped, showing the effect of reversing the merge (PR state back to master) instead of applying the merge (master to PR state).
Existing ordering (showing the bug - as `GVL_Motion.TcGVL` was removed in that linked PR):
```
lcls-plc-dream-motion$ git diff-tree --diff-filter=ACM -r HEAD  master --name-only |grep GVL
lcls-plc-dream-motion/lcls_dream_motion/GVLs/GVL_Motion.TcGVL
```
Correct (as in this PR):
```
lcls-plc-dream-motion$ git diff-tree …
```
=> FIX: correct order for diff-tree

.github/workflows/python-docs.yml, .github/workflows/python-pip-test.yml, .github/workflows/twincat-standard.yml
* Use `pip`-provided extras for testing and documentation building
* Remove support for installing deps from text files
* Remove default CI extras for installation
=> REF: pip-based testing/docs - use pyproject-specified extras

.github/workflows/python-docs.yml
In #127 we removed the default docs extras which were actually the only way anything was installed in the python environment for the docs deployment steps.
I think there's no reason for a package to customize the dependencies here, so I've opted to remove the docs extras wholesale and add in a simple `pip install docs-versions-menu`, which should be the only package needed to package up and deploy the docs.
=> FIX: ensure the docs upload requirement is available

.github/workflows/python-conda-test.yml
Pin back to pre-v8 and wait and see if there's ever a version with backwards compatibility
We would prefer if `write_to` returns, as an existing option, even if deprecated so that we can have a transition period, but it would not be enough- we also need a non-deprecated built-in way in setuptools_scm to write out the file ourselves prior to the conda build. Otherwise, another approach would be to update all of our tomls and write out a _version file ourselves via importing the internals, which seems fragile.
=> MAINT: setuptools_scm breaks API intentionally and silently at v8.0.0

.github/workflows/python-conda-test.yml
imp was removed in python 3.12
```
micromamba run -n upload mycommand
Traceback (most recent call last):
File "/home/runner/micromamba/envs/upload/bin/anaconda", line 6, in <module>
from binstar_client.scripts.cli import main
File "/home/runner/micromamba/envs/upload/lib/python3.12/site-packages/binstar_client/__init__.py", line 19, in <module>
from . import errors
File "/home/runner/micromamba/envs/upload/lib/python3.12/site-packages/binstar_client/errors.py", line 3, in <module>
from clyent.errors import ClyentError
File "/home/runner/micromamba/envs/upload/lib/python3.12/site-packages/clyent/__init__.py", line 5, in <module>
import imp
ModuleNotFoundError: No module named 'imp'
```
=> FIX: upload using python 3.11 to avoid a 3.12 compatibility issue

.github/workflows/python-conda-test.yml
Previously, `boa` depended on the `mamba` package which at present largely just includes a cli for the mamba solver under the `mamba` entrypoint. (this is my limited understanding, please don't get mad at me random github comment browser)
Now, `boa` doesn't depend on this wrapper, so `mamba` doesn't get installed and these two commands fail. I don't think we actually ever needed to use this entrypoint specifically, the rest of this file uses the `micromamba` entrypoint with no issues.
This hasn't been tested but the builds are pretty broken right now without a fix.
=> FIX: use micromamba instead of previously implicit mamba

.github/workflows/python-conda-test.yml, .github/workflows/python-pip-test.yml
Add tmate debugging to the standard python and conda workflows.
in our never ending quest to find a way to debug our ci jobs, I stumbled across this tmate action.  This allows us to directly access the runner machine, preventing us from trying and failing to build docker containers on our own.  
The new step is only activated on a manual workflow dispatch.  Once this workflow definition is in the main/master branch, you can go to the actions tab, pick the workflow, and run a job with a `workflow_dispatch` trigger.  Forks will run this on their own account (not using our github minutes!), or we can run this on our own pcdshub branches
(The below screenshot is a fork of tangkong/gha_test)
Getting direct access to the runner is a significant security risk.  There are a couple of mitigations …
=> BLD/TST: enable tmate debugging on manual workflow dispatch

.github/workflows/pre-commit.yml, .github/workflows/python-conda-test.yml, .github/workflows/python-docs.yml, .github/workflows/python-pip-test.yml, .github/workflows/twincat-pragmalint.yml, .github/workflows/twincat-style.yml, .github/workflows/twincat-summary.yml, .github/workflows/twincat-syntax.yml
Today I noticed some deprecation warnings in pcds-envs, which also needs a PR:
I did a find and replace for checkout@v3 -> checkout@v4
v4 was released back in October
=> MAINT: update to checkout v4 to avoid deprecation warning from v3

.github/workflows/python-conda-test.yml, .github/workflows/python-docs.yml, .github/workflows/python-pip-test.yml, .github/workflows/twincat-pragmalint.yml, .github/workflows/twincat-summary.yml, .github/workflows/twincat-syntax.yml
closes #141
I suppose there's no tests for the tests, but I think this should work ok.  We don't actually download any artifacts except for the documentation artifact, and the artifacts are all named differently anyway.
=> MNT: update setup-python and artifact actions for NodeJS compatibility

.github/workflows/python-standard.yml
This should only be merged when we get 3.12 fully working, otherwise we'll just get a bunch of ❌
=> BLD: add python 3.12 to the test matrix

.github/workflows/python-conda-test.yml
So, why not skip it?
```
$ mamba create --name verifytest python=3.12 conda-verify
Looking for: ['python=3.12', 'conda-verify']
pcds-tag/noarch                                               No change
pcds-tag/linux-64                                             No change
conda-forge/noarch                                  14.6MB @  29.5MB/s  1.3s
conda-forge/linux-64                                34.4MB @  21.7MB/s  3.8s
Could not solve for environment specs
The following packages are incompatible
├─ conda-verify is installable with the potential options
│  ├─ conda-verify [2.0.0|3.1.1] would require
│  │  └─ python [2.7* |>=2.7,<2.8.0a0 ], which can be installed;
│  ├─ conda-verify [2.0.0|3.1.1] would require
│  │  └─ python [3.5* |>=3.5,<3.6.0a0 ], which can be installed;
│  ├─ …
```
=> MAINT: python 3.12 builds are not getting past conda-verify step

.github/workflows/python-conda-test.yml, .github/workflows/python-pip-test.yml
We ran into some issues where GHE runners didn't like the read-all permissions, instead only allowing "all".
Also tmate debugging never managed to work, I can loop back to it later
=> CI: remove read-all permissions specification, non-operational tmate debugging

.github/workflows/python-standard.yml, .github/workflows/twincat-standard.yml
GHE currently does not like write permissions to gh-pages branch
we should re-enable this when either we
- get permission restrictions loosened by SLAC GHE
- figure out an alternate way of publishing docs (though most actions seem to require write permissions, obviously)
=> BLD: disable docs builds temporarily

.github/workflows/python-conda-test.yml, .github/workflows/python-pip-test.yml, .github/workflows/python-standard.yml, .github/workflows/twincat-standard.yml
Reverting changes from #147, now that GHE has fixed our permissions
=> BLD: reenable documentation builds, remove leftover tmate bits

.github/workflows/python-standard.yml
An experimental branch, we can choose not to go this route if we like.  I mostly want to stop filtering red ❌ on the BEAMS repo
Note: I'm requesting this branch be merged into the `pcdshub:pip_only` branch, not `master`
=> MNT: turn off conda tests in pip_only branch

.github/workflows/pre-commit.yml
The ubuntu-20.04 image runs python 3.8 which is too old for some of the twincat pre-commit builds.
Rather than keep using the old image, I opted to update to the 22.04 image that is currently tagged as "ubuntu-latest".
I could have also chosen 24.04 but since it wasn't tagged as latest I decided to only go up to 22.04.
List of builds:
https://github.com/actions/runner-images/tree/main
I then tried to run pre-commit on CI on a repo that was previously failing.
Failing build: https://github.com/pcdshub/lcls-twincat-math/actions/runs/11582459856/job/32245532359
My passing build: https://github.com/ZLLentz/lcls-twincat-math/actions/runs/11710367753/job/32616497674
I did not try this again on the python repos but I expect this to be transparent.
I am not currently interested in updating _all_ …
=> FIX: update pre-commit image to current ubuntu latest

.github/workflows/pre-commit.yml, .github/workflows/python-conda-test.yml, .github/workflows/python-docs.yml, .github/workflows/python-pip-test.yml, .github/workflows/twincat-pragmalint.yml, .github/workflows/twincat-style.yml, .github/workflows/twincat-summary.yml, .github/workflows/twincat-syntax.yml
Builds are starting to fail because of an ubuntu-20.04 brownout
ubuntu-20.04 as a runner os will be removed this month
This PR opts to switch us to always latest, which right now is ubuntu-24.04 and will automatically update when they release a new one.
It's not clear if this will give us problems in the future but we can adjust again without much pain.
=> MNT: update off of deprecated runner OS to latest

.github/workflows/python-docs.yml
Somehow we missed this in the earlier update.  I thought I grepped through the repo for all the ubuntu references but I guess I missed one
=> BLD/DOC: update docs deployment to ubuntu-latest

.github/CODEOWNERS, .github/workflows/pre-commit.yml, .github/workflows/python-conda-test.yml, .github/workflows/python-docs.yml, .github/workflows/python-pip-test.yml, .github/workflows/python-standard.yml, .github/workflows/twincat-pragmalint.yml, .github/workflows/twincat-standard.yml, .github/workflows/twincat-style.yml, .github/workflows/twincat-summary.yml, .github/workflows/twincat-syntax.yml
Commit history is a bit squirrely here, but beams wants to only use the pip tests.  This little dev branch fell behind master.
=> MNT: Update Pip only branch to use latest ubuntu runners

.github/workflows/python-standard.yml
As per the title.  Now that we're rolling out a 3.12 environment, we know that we won't need testing against the versions in between. We can also start testing compatibility with newer versions of python. 
One last thing that will need to be changed is the rulesets, which currently require 3.10 builds.  
Open to discussion as to where the deploy-on-success flag goes.  I think 3.12 is appropriate, but maybe we're not entirely there yet
=> MNT: update python test matrix to only require 3.9, 3.12.  Target 3.13, 3.14 as experimental

.github/workflows/python-docs.yml, .github/workflows/python-standard.yml
- Adjusts the python test matrices to include 3.9, 3.12, and 3.13
- 3.14 is only available in beta from github actions ([ref](https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json)), and not available at all on conda.  I think it's worth keeping the symmetrical
- Updates the docs builds to use python 3.12.
- This could have probably been done earlier.  I told myself to be more thorough and ended up targeting anything that had "3.9"
=> MNT: update python test matrix, attempt 2

.github/workflows/python-conda-test.yml
This was brought to my attention by Devan, and when I looked into it I couldn't find out where we actually run conda-verify.
I assume we've been "verifying" our recipes by  seeing if the rest of the job blows up
=> MNT: remove conda verify from conda tests, is unused and not supported for later python versions

.github/workflows/python-standard.yml
boa and mambabuild have been deprecated in favor of `rattler-build`, which needs a dedicated migration process.  
Until we organize that, we'll need to not have this job perma-failing.
https://rattler.build/latest/reference/recipe_file/#major-differences-from-conda-build
https://conda-forge.org/blog/2025/02/27/conda-forge-v1-recipe-support/
=> BLD: disable conda3.13 build
